kind: pipeline
name: default

workspace:
   base: /go
   path: src/github.com/fanux/fist/

steps:
- name: build-fist
  image: golang:1.12
  environment: 
    GO111MODULE: on
  commands:
     - go get -u golang.org/x/lint/golint
     - golint  -set_exit_status auth namespace rbac tools cmd template terminal
     - go build -o fist

- name: tryrun-fist
  image: golang:1.10.8
  commands:
    - ./fist auth -h
    - ./fist terminal -h
    - ./fist rbac -h

- name: publish-fist
  image: plugins/docker
  settings:
    repo: lameleg/fist
    tags: ${DRONE_TAG=latest}
    username:
      from_secret: docker-hub-user
    dockerfile: deploy/Dockerfile
    password:
      from_secret: docker-hub-pass
  when:
    event:
    - push

- name: deploy-template
  image: cuisongliu/drone-kube
  settings:
    template_repo: lameleg/fist
    template_tags: ${DRONE_TAG=latest}
  commands:
    - drone-kube template --deploy=deploy/template
  when:
    event:
      - push

- name: deploy-uninstall
  image: cuisongliu/drone-kube
  settings:
    kube_server:
      from_secret: k8s-server
    kube_ca:
      from_secret: k8s-ca
    kube_admin:
      from_secret: k8s-admin
    kube_admin_key:
      from_secret: k8s-admin-key
  commands:
    - drone-kube config
    - kubectl delete -f deploy/template  || true
    - sleep 5
  when:
    event:
    - push

- name: deploy-install
  image: cuisongliu/drone-kube
  settings:
    kube_server:
      from_secret: k8s-server
    kube_ca:
      from_secret: k8s-ca
    kube_admin:
      from_secret: k8s-admin
    kube_admin_key:
      from_secret: k8s-admin-key
  commands:
  - mkdir ~/.kube
  - cp deploy/config ~/.kube/config
  - kubectl delete -f rbac/deploy/deploy.yaml  || true
  - kubectl delete -f rbac/deploy/secret.yaml  || true
  - sleep 15
  - kubectl create -f rbac/deploy/secret.yaml  || true
  - kubectl create -f rbac/deploy/deploy.yaml  || true

- name: deploy-templates
  image: lachlanevenson/k8s-kubectl
  commands:
  - mkdir ~/.kube
  - cp deploy/config ~/.kube/config
  - kubectl delete -f template/deploy/deploy.yaml  || true
  - sleep 15
  - kubectl create -f template/deploy/deploy.yaml  || true
