apiVersion: apps/v1
kind: Deployment
metadata:
  name: fist-template
  namespace: sealyun
spec:
  replicas: 1
  selector:
    matchLabels:
      name: fist-template
  template:
    metadata:
      labels:
        name: fist-template
    spec:
      serviceAccountName: admin
      containers:
      - name: fist-template
        image: lameleg/fist:latest
        command: ["./fist", "template"]
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: fist-template
  namespace: sealyun
spec:
  type: NodePort
  clusterIP: 10.106.233.70
  ports:
  - name: fist-template
    port: 8080
    targetPort: 8080
    protocol: TCP
    nodePort: 32204
  selector:
    name: fist-template
